[package]
name = "ll1-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.15.0"
nom = "8.0.0"
strum = "0.27.0"
strum_macros = "0.27.0"
ungrammar = "1.16.1"

[dev-dependencies]
indoc = "2.0.5"
