[package]
name = "ll1-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.15.0"

[build-dependencies]
prettyplease = "0.2.29"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "2.0.98"
ungrammar = "1.16.1"

[dev-dependencies]
indoc = "2.0.5"
