QueryUnit ::= Query
Query ::= SelectQuery
SelectQuery ::= SelectClause DatasetClause* WhereClause
SelectClause ::= 'SELECT' ( 'DISTINCT' | 'REDUCED' )? ( Var+ | '*' )
DatasetClause ::= 'FROM' ( DefaultGraphClause | NamedGraphClause )
WhereClause ::= 'WHERE'? GroupGraphPattern
GroupGraphPattern ::= '{' ( SubSelect | GroupGraphPatternSub ) '}'
GroupGraphPatternSub ::= TriplesBlock?
TriplesBlock ::= TriplesSameSubjectPath ( '.' TriplesBlock? )?
TriplesSameSubjectPath ::= VarOrTerm PropertyListPathNotEmpty
VarOrTerm ::= Var | GraphTerm
Var ::= VAR1 | VAR2
GraphTerm ::= iri
iri ::= IRIREF
PropertyListPathNotEmpty ::= Var VarOrTerm ( ';' ( Var VarOrTerm )? )*
